# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 017e2ff4d6d3038ea860445fdef9fe6612257b660cd66e05df06953221efe02fb9c68c93c5dbdeb4e7888bc2cba440ef0774caf01efc1c8499b3c1d6d407b370

test:
  secret_key_base: bb56a9f5fa26a586cc8966aaca36426ce1a70e46e5bfcef60f65abd262db810987b45747431d4e6e6d1cc33e72f83f96b1f64a061a797e5b27bca32c2e6eb389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
